### PR TITLE
ClientSession maintains wrong connectFuture if Client creates a connection ("#connect") too quickly.

### PR DESCRIPTION
**Pull request by bgloeckle**
See comment in source.

### CODE REVIEW

**Comment by kuujo** [comment]
That test failure is unrelated. Still have yet to reproduce whatever is going on in that test.

**Comment by kuujo** [comment]
So, it looks like this can happen when `setupConnection` returns `CompletableFuture.completedFuture` right? That will occur when a `RegisterRequest` is being sent (no session is open yet), causing the future to be synchronously completed and then `null` to be assigned before the `connectFuture` is assigned.

But I think maybe this should be gone about another way. The semantics of threading in Copycat guarantee that asynchronous calls will not complete before the `connectFuture` is assigned. So, `setupConnection` should really just complete the future asynchronously to guarantee that the result of `setupConnection` is *always* asynchronous. This makes for a more consistent, easier to debug system. Copycat has some utilities for this:
```java
return Futures.completedFutureAsync(null, context.executor());
```

Ensuring that the behavior of each method is always consistent with regard to being synchronous or asynchronous ensures that these types of bugs don't arise in any other/future calls to the same method.

**Comment by bgloeckle** [comment]
Yes, that's right, my implementation of Client did return an already completed CompletableFuture. The workaround I now implemented basically is the same as your suggested solution by using `Futures.completedFutureAsync`: https://github.com/diqube/diqube/blob/master/diqube-consensus/src/main/java/org/diqube/consensus/internal/DiqubeCatalystClient.java#L60.

Basically, this PR is about the same issue for which I created #75 - copycat does depend on *when* (and in *what* thread) the CompletableFutures are completed. This means it depends on specific timings. `Client#connect` now is already called in the correct ThreadContext (and therefore on the correct thread), but then there is the next invariant that the timing needs to be correct - something that cannot be seen easily.
IMHO depending on correct timings is typically pretty problematic, as timings can easily be implemented wrong (like e.g. when implementing some custom code to work with a component, but also when extending the component itself), but bugs are hard to find (because it usually works "most of the time" and debugging is hard). I think, a component should always ensure that it can handle all timings used by source code "outside" of the component. We though could debate if the `Client` implementation is actually "outside" of copycat/catalyst.

The solution provided in this PR is fairly simple and it would spare guys who want to implement their own Connection/Client/... quite some headaches (and I guess that might be a lot of guys, as at least most people implementing enterprise software will not want to use unsecured Netty connections, but will rather wrap the calls by secured Servlet-calls etc.). It took me I guess several hours to identify the problem. 
If though you think it is not meaningful to merge this PR, at least the JavaDoc of `Client#connect` should be adjusted to point out that the returned future has to be completed *asynchronously* on the current thread context and/or a general documentation for guys who want to use copycat for their implementations should be created, that points out that e.g. "all returned CompletableFutures always have to be completed on the correct ThreadContext (on the current one, if none is passed to the function) and always have to be completed asynchronously" (only if that statement is true, of course).

**Comment by kuujo** [comment]
The client has been completely rewritten to be more testable and better manage connections since this was opened. Reopen if this issue is present in the new client.

**Pull request closed without merging**
