### PR TITLE
Avoids ConcurrentModificationException in ClientSessionSubmitter::close

### PR DESCRIPTION
**Pull request by madjam**
This PR fixes a bug in `ClientSessionSubmitter::close` method that can lead to a `ConcurrentModificationException`. When this happens it impacts client session recovery.

### CODE REVIEW

**Comment by kuujo** [comment]
Just to make sure I'm getting this, we're replacing `LinkedHashMap` with `HashMap` and then sequencing the exception to ensure they occur in the correct order?

**Comment by madjam** [comment]
LinkedHashMap change is just a simple optimization. By providing an insertion order iteration over values it lets us abort attempts in the order in which they are initiated. 

The key change is avoidance of concurrent modification of the map during iteration.

**Comment by kuujo** [comment]
👍

**Comment by kuujo** [comment]
I did see some test failures but they seem unrelated and I'll try to reproduce them separately.

**Comment by madjam** [comment]
Great. Sounds good.

**Pull request merged**
